// Interface strings of the 3D model. French for the guide, English for the stand-alone copy.
export const STRINGS = {
  fr: {
    pageTitle: 'Maquette 3D — Villa Colbert',
    srTitle: 'Maquette 3D interactive de Villa Colbert, 4 et 4 bis rue du Pont Colbert',
    eyebrow: 'Versailles · Yvelines',
    factLevels: 'RDC + 6 niveaux',
    factFacade: 'façade',
    factFaces: 'façade sur rue orientée',
    noteStrong: 'Maquette approximative.',
    note: 'Volumes, niveaux, façade sur rue, parkings et accès au 4 bis relevés sur Street View (février 2026), vue aérienne et indications de résidents ; le côté jardin est extrapolé.',
    canvas: 'Maquette 3D de Villa Colbert. Faites glisser pour tourner autour de la résidence.',
    north: 'Nord',
    dock: 'Commandes de la maquette',
    viewLabel: 'Vue',
    viewGroup: 'Points de vue',
    views: {
      street: 'Façade sur rue', nw: 'Côté nord-ouest', se: 'Angle sud-est',
      garage: 'Parkings & 4 bis', garden: 'Côté jardin', aerial: 'Vue aérienne',
    },
    orbit: 'Visite', orbitTitle: 'Va-et-vient lent entre les vues 2, 1 et 3 (espace) — reprend seul une minute après votre dernier geste',
    floors: 'Étages', floorsTitle: 'Afficher les niveaux et les dimensions',
    seasonGroup: 'Date pour la course du soleil',
    seasons: { winter: 'Hiver', equinox: 'Équinoxe', summer: 'Été' },
    seasonTitles: { winter: '21 décembre', equinox: '20 mars / 22 septembre', summer: '21 juin' },
    sunLabel: 'Soleil', sunSlider: 'Heure de la journée (heure locale, Versailles)', localTime: 'heure locale',
    day: 'Journée', dayTitle: 'Jouer la journée : le soleil et les ombres se déplacent',
    sunRead: (az, alt) => `az. ${az}° · haut. ${alt}°`, sunDown: 'soleil couché',
    hint: 'Faites glisser pour tourner · molette pour zoomer · clic droit pour déplacer',
    hintTouch: 'Faites glisser pour tourner · pincez pour zoomer',
    hintHero: 'Faites glisser pour tourner autour de la résidence',
    loading: 'Assemblage de la façade…',
    errEngine: 'Le moteur 3D ne s’est pas chargé. Vérifiez la connexion puis rechargez la page.',
    errWebgl: 'Ce navigateur ne peut pas afficher la 3D (WebGL indisponible).',
    errBuild: 'La maquette n’a pas pu être construite : ',
    floorNames: ['RDC', '1er', '2e', '3e', '4e', '5e', '6e · attique'],
    dimHeight: (h) => `≈ ${h} m de haut`, dimLength: '≈ 53 m', dimDepth: '≈ 24 m avec l’aile',
    landmark: (n) => `Voir l’entrée ${n}`,
  },
  en: {
    pageTitle: '4 & 4 bis rue du Pont Colbert',
    srTitle: '3D model of 4 and 4 bis rue du Pont Colbert, Versailles',
    eyebrow: 'Versailles · Yvelines',
    factLevels: 'RDC + 6 levels',
    factFacade: 'façade',
    factFaces: 'street front faces',
    noteStrong: 'Approximate model.',
    note: 'Massing, floor count, the street façade and the parking / 4 bis entrances are traced from Street View (Feb 2026), aerial imagery and residents’ corrections; the garden side is extrapolated.',
    canvas: '3D model of 4 and 4 bis rue du Pont Colbert. Drag to orbit, scroll to zoom.',
    north: 'North',
    dock: 'Viewer controls',
    viewLabel: 'View',
    viewGroup: 'Viewpoints',
    views: {
      street: 'Street front', nw: 'From the NW', se: 'SE corner',
      garage: 'Parking & 4 bis', garden: 'Garden side', aerial: 'Aerial',
    },
    orbit: 'Tour', orbitTitle: 'Slow back-and-forth between views 2, 1 and 3 (space) — resumes a minute after your last move',
    floors: 'Floors', floorsTitle: 'Show floor levels and overall dimensions',
    seasonGroup: 'Date for the sun path',
    seasons: { winter: 'Winter', equinox: 'Equinox', summer: 'Summer' },
    seasonTitles: { winter: '21 December', equinox: '20 March / 22 September', summer: '21 June' },
    sunLabel: 'Sun', sunSlider: 'Time of day (local time, Versailles)', localTime: 'local time',
    day: 'Day', dayTitle: 'Play the day: watch the sun and shadows move',
    sunRead: (az, alt) => `az ${az}° · alt ${alt}°`, sunDown: 'sun below horizon',
    hint: 'Drag to orbit · scroll or pinch to zoom · right-drag to pan',
    hintTouch: 'Drag to orbit · pinch to zoom · two fingers to pan',
    hintHero: 'Drag to orbit around the building',
    loading: 'Assembling the façade…',
    errEngine: 'The 3D engine did not load. Check your connection, then reload the page.',
    errWebgl: 'This browser could not start WebGL, which the 3D model needs. Try another browser or device.',
    errBuild: 'Something went wrong while building the model: ',
    floorNames: ['RDC', '1er', '2e', '3e', '4e', '5e', '6e · attique'],
    dimHeight: (h) => `≈ ${h} m high`, dimLength: '≈ 53 m', dimDepth: '≈ 24 m with wing',
    landmark: (n) => `Show entrance ${n}`,
  },
};

export const VIEW_ORDER = ['street', 'nw', 'se', 'garage', 'garden', 'aerial'];
