// Public professional channels only. No resident details, private direct lines or contract identifiers.
export const contacts = [
{id:'syndic',role:'Syndic et suivi des demandes',company:'Homeland',phone:'01 86 760 760',email:'assistance@homeland.immo',url:'https://extranet.homeland.immo/',status:'Interlocuteur confirmé',note:'Premier contact pour les parties communes, les demandes d’intervention, les sinistres collectifs et les questions de charges. Assistance annoncée 24 h/24 et 7 j/7.',source:'AG du 13 avril 2026, résolution 8 ; échanges d’octobre 2026 ; site Homeland.',refs:['https://www.homeland.immo/theme/suivez-le-guide']},
{id:'ascenseurs',role:'Ascenseurs',company:'TK Elevator',phone:'0800 24 00 20',url:'https://www.tkelevator.com/fr-fr/contact/',status:'Contrat retrouvé',note:'Dépannage 24 h/24 et 7 j/7. Utilisez en priorité l’alarme et les instructions de la cabine. Pour une clé tombée dans la fosse, demandez une récupération au mainteneur : aucun tarif ni gratuité n’est garanti ici.',source:'Contrat étendu 2025, retransmis le 2 octobre 2026 ; contact officiel TK Elevator.'},
{id:'portes-parking',role:'Portes automatiques des parkings',company:'SFPA',phone:'01 69 30 24 15',email:'depannage@sfpa-portes.fr',status:'Contrat et suivi 2026 retrouvés',note:'Signalez la panne à Homeland pour l’organisation de l’intervention. Le contrat demande un signalement par email ; accueil téléphonique du lundi au vendredi, 8 h–12 h et 13 h 30–17 h, hors jours fériés. Ne manipulez pas le mécanisme.',source:'Contrat de maintenance des deux portes basculantes signé en mars 2024 ; échange du syndic du 4 mars 2026.'},
{id:'eau-chaude',role:'Production collective d’eau chaude',company:'Tournois',phone:'01 39 56 05 09',status:'Contrat retrouvé',note:'Contact de dépannage indiqué au contrat en jours et heures ouvrés. Prévenez Homeland en précisant si plusieurs logements sont touchés. Ce numéro n’est pas présenté comme une astreinte permanente.',source:'Contrat d’entretien de la production d’eau chaude et du traitement d’eau, effet au 19 juin 2024 ; AG du 13 avril 2026 et suivi des travaux 2026.',refs:['https://www.villedebuc.fr/151-269/a-votre-service/commerces-et-entreprises/annuaire-des-commerces-et-entreprises/ficheAnnu/tournois-services-sas.htm']},
{id:'chauffage',role:'Trames de chauffage collectif',company:'SETEMI',phone:'01 41 44 82 82',url:'https://www.setemi.fr/',status:'Intervenant confirmé en 2026',note:'Transmettez le signalement à Homeland : pièce, dates, températures relevées et symptômes. Les opérations sur les trames et leur alimentation relèvent des professionnels.',source:'Visite de maintenance du 21 janvier 2026 et échanges d’octobre 2026 ; téléphone du site officiel.'},
{id:'compteurs',role:'Compteurs et télérelève',company:'OCEA Smart Building',phone:'0 800 382 382',url:'https://www.groupe-ocea.fr/aide-contact/faq-habitat/',status:'Contrat et intervention retrouvés',note:'Contact opérationnel public. Pour un relevé ou un accès à votre suivi de consommation, consultez OCEA. Pour le tarif appliqué ou une régularisation de charges, contactez Homeland. L’offre signée prévoit la pose des robinets d’arrêt, mais l’option d’entretien n’est pas cochée. Faites vérifier tout avenant avant de demander une prise en charge.',source:'Contrat OCEA 2023, intervention confirmée par le syndic en janvier 2025 ; FAQ officielle OCEA consultée le 6 octobre 2026.'},
{id:'vmc',role:'Ventilation mécanique contrôlée',company:'AVH Services',phone:'01 34 78 58 66',url:'https://www.avh-services.com/',status:'Intervenant confirmé en 2026',note:'Signalez au syndic le bruit, l’odeur ou l’anomalie d’extraction et la pièce concernée. Demandez l’organisation d’une intervention sur le réseau collectif.',source:'Ordre de mission et échanges VMC de 2026 ; numéro actuel du site officiel, différent de l’ancien Abécédaire.'},
{id:'entretien',role:'Nettoyage des parties communes',company:'ANET & Services',phone:'01 39 53 33 39',email:'anetservices@yahoo.fr',status:'Contrat retrouvé',note:'Pour une anomalie de nettoyage, indiquez au syndic le lieu et la date. Le changement d’une ampoule est prévu sur demande : le contrat précise que seule la fourniture de l’ampoule est facturée. Les autres défauts électriques nécessitent un diagnostic distinct.',source:'Contrat accepté le 7 juillet 2023, retransmis le 2 octobre 2026 ; adresse professionnelle également utilisée dans les échanges de décembre 2025.'},
{id:'jardins',role:'Espaces verts',company:'Concept du Paysage',phone:'01 34 86 03 85',email:'cdp@conceptdupaysage.fr',url:'https://conceptdupaysage.com/contact/',status:'Contrat retrouvé ; contact public actualisé',note:'Adressez les besoins et propositions concernant les plantations communes au syndic ou au conseil syndical. Les commandes sont organisées par la copropriété.',source:'Contrat du 23 juin 2022 et comptes 2024 revus en 2025 ; coordonnées du site officiel consultées le 6 octobre 2026.'},
{id:'interphone',role:'Interphone et contrôle d’accès',company:'Précisélec',phone:'01 39 46 77 63',url:'https://www.preciselec.net/contact/',status:'Interventions documentées ; périmètre à confirmer',note:'Pour un badge perdu, une commande de badge ou un défaut d’interphone, passez par Homeland. Le périmètre de maintenance actuel doit être confirmé avant une intervention directe.',source:'Dépense d’intervention confirmée dans les échanges comptables de 2025 ; coordonnées publiques actuelles Précisélec.'},
{id:'incendie',role:'Équipements de sécurité incendie',company:'Bouvier / Sagex Bouvier BSI',status:'Contrats retrouvés ; contact direct à confirmer',note:'Pour une anomalie d’extincteur, de désenfumage ou de porte coupe-feu, contactez Homeland. En présence d’un incendie ou d’un danger immédiat, appelez les secours.',source:'Contrats conservés dans l’extranet et suivi 2026. Contrats distincts pour extincteurs, éclairage de sécurité, désenfumage et portes coupe-feu ; numéro d’intervention actuel à confirmer.'},
{id:'toiture',role:'Toiture et étanchéité',company:'Cabinet Minne · étude de réfection',status:'Mission votée en AG',note:'Pour une infiltration ou un suivi des travaux, contactez Homeland. Le cabinet Minne a été retenu pour l’étude et la consultation des entreprises ; cette mission ne constitue pas un service de dépannage.',source:'AG du 13 avril 2026, résolution 15.2. Anciens contrats ADEBAT et intervenants ponctuels à rapprocher des missions encore actives.'},
{id:'diagnostics',role:'Contrôles et diagnostics',company:'CASTE ING · Diag at Home',status:'Missions signalées en octobre 2026',note:'Ces missions sont organisées par le syndic : contrôle quinquennal des ascenseurs et diagnostic amiante. Pour une question de planning ou de périmètre, contactez Homeland.',source:'Échanges des 5 et 6 octobre 2026. CASTE ING : coordonnées générales sur son site.',url:'https://www.caste-ing.com/'},
{id:'autres',role:'Vide-ordures, nuisibles et autres équipements',company:'Orientation par Homeland',status:'Périmètres à revalider',note:'Des contrats historiques SICRE LEMAIRE (colonnes de vide-ordures) et EBA Préventim (termites) existent. Leur présence dans les archives ne suffit pas à établir une mission actuelle. Demandez au syndic le professionnel à mandater.',source:'Inventaire des contrats de l’extranet ; absence de confirmation récente suffisante.'},
{id:'dechets',role:'Déchets et encombrants',company:'Versailles Grand Parc',url:'https://www.versaillesgrandparc.fr/927.htm',status:'Service public à consulter',note:'Vérifiez les jours de collecte, les filières et les déchèteries à partir de votre adresse. Les anciennes coordonnées d’une entreprise d’enlèvement ne remplacent pas les consignes actuelles.',source:'Service public de collecte de Versailles Grand Parc.'}
];
