export function enrich(articles){
const get=s=>articles.find(a=>a.slug===s);
const append=(s,h,p)=>get(s).sections.push([h,p]);
const old='Anciennes pages FAQ et Bon voisinage, captures PDF du 11 février 2025 ; actualisation éditoriale du 6 octobre 2026.';
append('arriver-et-demenager','Un déménagement respectueux',['Protégez les parois et le sol de l’ascenseur, respectez la charge affichée et laissez les portes fonctionner normalement. Prévenez les voisins et organisez le passage des objets volumineux.']);
append('bruit-et-voisinage','Limiter les bruits transmis par les sols',['Des chaussons à semelles souples et des patins en feutre sous les chaises et meubles réduisent les bruits du quotidien. Prévenez vos voisins avant une fête ou des travaux bruyants.','La page historique cite un arrêté de 1998. Pour les horaires actuels, consultez les informations de la Ville de Versailles et les règles applicables à votre chantier.']);
get('bruit-et-voisinage').links=[...(get('bruit-et-voisinage').links||[]),['Bruit : informations de la Ville de Versailles','https://www.versailles.fr/156/mairie/prevention-et-securite/hygiene.htm']];
append('boites-aux-lettres','Courrier, publicité et absences',['Un autocollant « Stop Pub » permet de signaler votre souhait de ne pas recevoir d’imprimés publicitaires non adressés. Il ne concerne pas les courriers adressés à votre nom.','Pendant une absence, convenez en privé avec une personne de confiance de relever votre courrier. Ne publiez pas vos dates d’absence sur le site.','Le PV de 2016 demande des plaques harmonisées : texte en majuscules, noir sur blanc, avec Copperplate Gothic si possible. Faites confirmer le modèle et les dimensions actuellement utilisés avant fabrication ; le tarif ancien ne constitue pas un devis actuel.']);
append('ascenseurs','Un objet ou des clés tombés dans la fosse',['Contactez le mainteneur pour organiser la récupération. N’ouvrez pas les portes palières et ne tentez pas d’accéder à la fosse. La gratuité et le tarif d’environ 100 € évoqués dans l’ancienne FAQ en 2015 ne sont pas reconduits.']);
get('ascenseurs').pending='Modalités et coût de récupération des objets à demander au mainteneur. Contact actuel : annuaire « Qui contacter ? ».';
append('chauffage-et-trames','Comprendre le chauffage de base',['La FAQ historique décrit une base collective par trames et un complément par convecteurs individuels. Elle cite environ 13 °C au titre du règlement de copropriété ; ce chiffre n’est pas présenté ici comme une garantie mesurée aujourd’hui.','Les trames chauffent la structure et leur effet est progressif. Pour documenter un défaut, relevez la température matin et soir, dans la même pièce et au même endroit, avec date et heure.','L’ancienne période de chauffe ne doit pas être appliquée automatiquement : les échanges d’octobre 2026 discutent encore la date de remise en marche. Consultez l’annonce actuelle du syndic.']);
append('eau-chaude-et-compteurs','Comprendre la facturation',['Le tarif voté à l’AG du 13 avril 2026 est de 34 €/m³, avec effet au 1er janvier 2026, contre 37 € auparavant. Le syndic est chargé des régularisations. Consultez l’historique des décisions ci-dessous pour les étapes antérieures.','OCEA intervient sur les compteurs et leur suivi. Le syndic reste l’interlocuteur pour le prix appliqué et les charges : le prestataire de comptage ne décide pas du tarif de la copropriété.']);
append('eau-chaude-et-compteurs','Une eau froide qui arrive tiède',['La FAQ décrit une observation et une analyse de 2015 concernant la proximité des réseaux dans les gaines. Ce diagnostic historique ne suffit pas à expliquer chaque anomalie actuelle.','Notez le robinet concerné, la durée du phénomène et les moments où il se produit ; transmettez ces observations au syndic. Ne modifiez pas vous-même les gaines ou l’isolation des réseaux communs.']);
get('eau-chaude-et-compteurs').pending='Application effective du nouveau tarif aux comptes individuels et périmètre d’entretien des robinets à confirmer. Les prestataires de production et de comptage sont identifiés dans l’annuaire.';
get('eau-chaude-et-compteurs').sections=get('eau-chaude-et-compteurs').sections.filter(([h])=>h!=='Anciennes consignes à revalider');
append('ventilation-vmc','Préserver les entrées d’air',['N’obstruez pas les entrées d’air ni les bouches d’extraction. Pour un bruit inhabituel, demandez un contrôle ; l’ancienne astuce consistant à laisser une fenêtre ouverte ne remplace pas la recherche de la cause.']);
append('dechets-et-encombrants','Avant de jeter',['Lorsque l’objet est réutilisable, privilégiez le don, la réparation ou le réemploi. Pour le compostage et les collectes spécialisées, vérifiez les possibilités et modalités actuelles auprès de Versailles Grand Parc.','Les lieux, jours de collecte et événements datés de l’ancienne page ne sont pas repris comme calendrier actuel.']);
get('dechets-et-encombrants').related.push('reemploi-et-compost');
get('parking-et-stationnement').sections.find(([h])=>h==='Panne de porte')[1]=['Signalez le défaut à Homeland pour l’intervention de SFPA. Les coordonnées et horaires du contrat sont dans l’annuaire. Ne manipulez pas le mécanisme.'];
get('parking-et-stationnement').pending='Consignes locales de circulation à confirmer ; l’annuaire donne le circuit de dépannage documenté.';
get('urgences').sections.find(([h])=>h==='Contacts de la résidence')[1]=['L’annuaire « Qui contacter ? » rassemble les coordonnées professionnelles et les circuits documentés. Les anciens noms et numéros non confirmés ne doivent pas servir de référence.'];
get('urgences').pending='Suivez aussi les consignes affichées sur place. Les coordonnées du CS et des résidents restent privées.';
get('signaler-un-probleme').pending='Pour le destinataire adapté à chaque équipement, consultez « Qui contacter ? ». Les coordonnées privées ne figurent pas sur le site public.';

get('ascenseurs').sections=get('ascenseurs').sections.filter(([h])=>h!=='Ce qui n’est pas confirmé');
get('chauffage-et-trames').sections=get('chauffage-et-trames').sections.filter(([h])=>h!=='À compléter');
get('eau-chaude-et-compteurs').pending='Application effective du tarif aux comptes individuels, option d’astreinte Tournois et éventuel avenant OCEA sur l’entretien des robinets à confirmer.';
get('eclairage').sections=get('eclairage').sections.map(([h,items])=>[h,items.map(t=>t.startsWith('La répartition des interventions')?'Pour une ampoule commune défectueuse, le contrat ANET prévoit un changement sur demande, avec facturation de la fourniture. Un défaut de circuit ou de luminaire nécessite un diagnostic distinct. Ne démontez pas les équipements communs.':t)]);
get('eclairage').pending='Faire diagnostiquer les défauts de luminaire ou de circuit ; ils ne relèvent pas automatiquement de la prestation de changement d’ampoule.';
const additions=[
{slug:'recharge-vehicules-electriques',title:'Recharge des véhicules électriques',letter:'R',category:'Équipements',icon:'car',intro:'Comprendre les votes sur la recharge et préparer une demande de raccordement avec le syndic.',keywords:'borne recharge IRVE voiture électrique parking WAAT Zeplug Electro-Mob Enedis',sections:[['Avant de commander une borne',['Adressez votre demande à Homeland en précisant le besoin de raccordement. Faites confirmer l’opérateur retenu, le périmètre de l’infrastructure et les modalités applicables.','Ne déduisez pas d’un vote d’AG qu’une installation est déjà en service. Les archives présentent plusieurs projets successifs : ils sont distingués dans l’historique ci-dessous.']],['Qui intervient ?',['Electro-Mob figure dans une proposition d’infrastructure adoptée en 2024. Les conventions signées, la réception et le titulaire effectif de l’exploitation restent à rapprocher de ce vote.','En attendant cette confirmation, Homeland est l’interlocuteur pour orienter la demande. Aucun numéro de dépannage de recharge non vérifié n’est publié.']],['Coût et entretien',['Demandez séparément le prix du raccordement, celui de la borne individuelle, les conditions de consommation et d’abonnement, ainsi que les responsabilités d’entretien.','Le financement d’une infrastructure collective ne signifie pas que tous les frais individuels sont pris en charge.']]],pending:'Convention en vigueur, opérateur, mise en service, raccordement individuel et maintenance à confirmer par Homeland.',source:'PV des AG des 28 septembre 2020, 23 juin 2021, 17 mai 2022, 27 juin 2023 et 28 juin 2024 ; références détaillées dans l’historique.',related:['parking-et-stationnement','travaux-privatifs','conseil-syndical-et-syndic']},

{slug:'whatsapp',title:'WhatsApp : résidents et conseil syndical',letter:'W',category:'Vie quotidienne',icon:'message',intro:'Deux groupes, deux usages : l’entraide entre résidents et la coordination du conseil syndical.',keywords:'whatsapp groupe résident conseil syndical CS QR code rejoindre invitation administrateur',sections:[['Le groupe des résidents',['Il est destiné aux résidents de Villa Colbert, propriétaires occupants et locataires : informations pratiques, entraide et vie de la résidence.','Pour demander à le rejoindre, adressez-vous en privé à un administrateur du groupe ou à votre interlocuteur au conseil syndical. Le Petit Colbert de septembre 2025 indiquait des QR codes affichés dans les entrées du 4 et du 4 bis ; leur validité actuelle reste à vérifier.']],['Le groupe du conseil syndical',['Ce groupe est réservé aux membres du conseil syndical en fonction. Il sert à coordonner les sujets et le suivi du CS.','Être résident ou copropriétaire ne donne pas automatiquement accès à ce groupe. La demande doit être vérifiée par un administrateur au regard de la composition actuelle du CS.']],['Participer avec attention',['Restez courtois, gardez les échanges utiles à la résidence et demandez l’accord des personnes avant de diffuser leurs coordonnées ou leurs messages.','Un message WhatsApp ne remplace pas une demande d’intervention adressée au syndic. Pour une urgence, utilisez les contacts de dépannage ou les secours.','Les documents personnels, informations d’accès et dossiers individuels restent dans les échanges privés appropriés.']]],pending:'Liens de demande d’adhésion et validation par les administrateurs à confirmer avant publication des QR codes. Aucun lien d’invitation n’est actuellement publié.',source:'Organisation des deux groupes précisée par le porteur du projet le 6 octobre 2026 ; Petit Colbert de septembre 2025, version 2 transmise le 22 septembre 2025 pour le groupe résidents.',related:['conseil-syndical-et-syndic','signaler-un-probleme','absences-et-securite']},
{slug:'absences-et-securite',title:'Absences et sécurité',letter:'A',category:'Vie quotidienne',icon:'home',intro:'Organiser une absence et prendre soin des accès, sans exposer les informations des résidents.',keywords:'absence vacances courrier porte badge perte sécurité voisin',sections:[['Préparer une absence',['Conservez en privé les coordonnées d’une personne de confiance. Convenez avec elle du relevé du courrier ou d’un autre besoin pratique. Évitez les annonces publiques de dates d’absence.']],['Accès et badges',['Assurez-vous que les portes se referment derrière vous et signalez un défaut de fermeture. Ne communiquez pas les informations d’accès sur le site public.','Pour un badge perdu ou volé, prévenez le syndic. Les commandes et les éventuelles désactivations doivent suivre le circuit de la résidence.']],['Annuaire des résidents',['Les coordonnées personnelles du conseil syndical, des voisins et des référents sont à consulter par les canaux privés de la résidence. Le site public fournit seulement les coordonnées professionnelles et les numéros de dépannage retenus.']]],pending:'Organisation d’un espace résidents avec accès individuel proposée ; aucun annuaire privé n’est hébergé sur ce site.',source:old,related:['arriver-et-demenager','boites-aux-lettres','urgences']},
{slug:'reemploi-et-compost',title:'Réemploi et compost',letter:'R',category:'Vie quotidienne',icon:'leaf',intro:'Donner une seconde vie aux objets et trouver les filières adaptées aux déchets organiques.',keywords:'compost biodéchet don réparation réemploi gratiferia bouchon livres',sections:[['Donner et réutiliser',['Avant un dépôt aux encombrants, vérifiez si l’objet peut être donné ou réparé. Convenez directement avec le destinataire du transport et du rendez-vous.','Une collecte ponctuelle ou un espace de partage doit être organisé sans encombrer les circulations.']],['Composter et participer',['L’ancien site mentionne un compost de quartier et des initiatives de partage. Demandez à Versailles Grand Parc les sites et modalités d’inscription actuellement disponibles.','Les anciens noms de référents, dates de gratiferias et lieux de dépôt bénévoles doivent être reconfirmés avant d’orienter les résidents.']]],pending:'Fonctionnement actuel des initiatives propres à la résidence à confirmer avec leurs organisateurs.',source:old,links:[['Versailles Grand Parc','https://www.versaillesgrandparc.fr/']],related:['dechets-et-encombrants','jardins-et-vie-de-residence']},
{slug:'toiture-et-projets',title:'Toiture et projets collectifs',letter:'T',category:'Travaux & logement',icon:'tool',intro:'Distinguer une étude, un vote de travaux et leur réalisation, avec un historique par sujet.',keywords:'toiture terrasse étanchéité architecte Minne diagnostic DTG DPE PPPT plan pluriannuel',sections:[['Étudier avant de commander les travaux',['Une mission de diagnostic ou de consultation prépare le choix des travaux. Elle n’établit ni le coût final du chantier ni son achèvement.','L’AG du 13 avril 2026 a retenu le cabinet Minne pour l’étude de la toiture et l’appel d’offres. L’historique ci-dessous reprend les décisions qui l’ont précédée.']],['Suivre les diagnostics',['Les offres de DTG et les variantes DPE/PPPT présentées en 2026 ont été rejetées. L’historique doit aussi conserver l’ambiguïté du texte voté en 2025.','Pour les documents applicables, les devis et l’état d’avancement détaillé, consultez l’extranet ou le syndic.']],['Signaler une infiltration',['Décrivez l’emplacement, la date, les conditions d’apparition et les dommages visibles. Prévenez le syndic et votre assurance lorsque votre logement est touché.']]],pending:'Clarification du DTG 2025, avancement de l’étude de toiture et futures décisions de travaux à compléter.',source:'PV des AG du 8 avril 2025 et du 13 avril 2026, synthèse non nominative.',related:['fuites-et-degats-des-eaux','conseil-syndical-et-syndic','travaux-privatifs']}
];
articles.push(...additions);
get('conseil-syndical-et-syndic').related.push('whatsapp');
get('parking-et-stationnement').related.push('recharge-vehicules-electriques');
append('reemploi-et-compost','Distinguer le quartier et la résidence',['Les projets de compost collectif propres à la résidence soumis aux AG de 2015, 2016 et 2020 ont été rejetés. Ces votes ne concernent pas automatiquement les dispositifs du quartier. Consultez l’historique ci-dessous et faites confirmer les possibilités actuelles.']);
append('conseil-syndical-et-syndic','Pourquoi un Abécédaire ?',['L’AG de 2013 demandait déjà d’enrichir l’Abécédaire avec les éléments utiles du règlement intérieur. Le guide aide à trouver les règles de vie, le bon interlocuteur et l’origine des décisions. Il ne remplace pas les documents applicables.']);

get('arriver-et-demenager').related.push('whatsapp');
for(const s of ['arriver-et-demenager','bruit-et-voisinage','boites-aux-lettres','ascenseurs','chauffage-et-trames','eau-chaude-et-compteurs','ventilation-vmc','dechets-et-encombrants'])get(s).source+=' '+old;
articles.sort((a,b)=>a.title.localeCompare(b.title,'fr'));
}
